<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MSI" failures="1" tests="1" name="testRunner.Runner" time="66.079" errors="0" timestamp="2025-05-29T18:13:56 IST" skipped="0">
  <testcase classname="testRunner.Runner" name="runScenario" time="66.079">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at StepActions.stepActions.verifyOrderConfirmationMessage(stepActions.java:123)
at stepDefinition.stepDefinitions.getOrderConfirmationMessage(stepDefinitions.java:78)
at âœ½.get the order confirmation message(file:///C:/Users/manav/miniProject/src/test/resources/features/Project.feature:17)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- testRunner.Runner -->
